csv_path: ../data/train.csv
train_data_path: ./csv_store/train_data.csv
val_data_path: ./csv_store/val_data.csv
crop_path: ../data/yolo_preds_v2.csv
num_workers: 0
epochs: 5
batch_size: 128
image_size: 128
last_linear_lr: 1.6e-2
lr:  1.6e-3
backbone: resnet18
seed:  42
path: ../data/train/
device: cuda
save_path: ./model_store/resnet18.pt
es_patience: 5
embedding_size: -1
warmup_steps_ratio: 0.2
lr_decay_scale: 1.0e-2
m: 0.35
s: 32.0
run_name: initial_run
trial_path: trial_store
loss_name: cosine_margin
num_classes: 5004